"""add recipe fields

Revision ID: 6886f7d6d4a7
Revises: 9c59e5aa650a
Create Date: 2026-07-17 19:16:47.870085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6886f7d6d4a7'
down_revision: Union[str, Sequence[str], None] = '9c59e5aa650a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('recipes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('prep_time_min', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('cook_time_min', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('source', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_recipes_slug'), 'recipes', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_recipes_slug'), 'recipes', type_='unique')
    op.drop_column('recipes', 'source')
    op.drop_column('recipes', 'cook_time_min')
    op.drop_column('recipes', 'prep_time_min')
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'description')
    op.drop_column('recipes', 'slug')
    # ### end Alembic commands ###
